### ISSUE TITLE
Self attention的结果如何输入到cross attention

### ISSUE THREAD

**Issue by sunxiaoyao-git** [zhangyichent/TimeXer#1]
作者你好！感谢你写了这么完整的TimeXer的代码！我看完后有一个问题想向你请教一下：TimeXerEncoderLayer中，Self attention得到的X1是不是应该取variate embedding部分去做cross attention？我看你的代码里面没有拆分
![image](https://github.com/user-attachments/assets/14bc8887-0d8c-4802-adb9-0cf1276477bf)

**Comment by zhangyichent** [comment]
我是按照我对这个图的理解去做的，不一定对，仅供参考。你说的拆分是个什么意思？没get到啊。。
![1724210233(1)](https://github.com/user-attachments/assets/e21760b3-f360-4249-8e36-b8f0a8661e52)

**Comment by sunxiaoyao-git** [comment]
x1包含了variate embedding和普通的embedding？

**Comment by niyasama** [comment]
确实有这样的问题，原论文似乎需要拆分序列

**Comment by sunxiaoyao-git** [comment]
静候原论文作者发code了
