### ISSUE TITLE
too many bug

### ISSUE THREAD

**Issue by JasonCZH4** [zhangyichent/TimeXer#3]
Glad to see that a paper has open-source code.
But too many unused function argument is defined. Caused runtime error.
Here are some example.
In `timexer.py`, no cross_attention is defined in `self.encoder`. But in `Transformer_EncDec.py`, the TimeXerEncoderLayer module require one to initiate.
Again, `configs.embed, configs.freq` never use in DataEmbedding_inverted, but pass when initiating `self.exo_i_embedding`.
Hope to clean the code to improve readability.

**Comment by zhangyichent** [comment]
Haha, there is indeed a lot of redundant stuff in the code. I didn't really go through it carefully; I just made sure it could run and that the results were similar to those in the paper. I'll take the time to clean it up later. Anyway, thanks for pointing it out.
